### PR TITLE
Change version file to more appropriate name

### PR DESCRIPTION
**Pull request by tmarcu**
Signed-off-by: Tudor Marcu tudor.marcu@intel.com

### CODE REVIEW

**Comment by tmarcu** [comment]
Must be merged with chroot builder changes.

**Comment by phmccarty** [comment]
+1

**Review by phmccarty — COMMENTED** [review]
The same change is needed for basic-creator.sh and mk_groups_ini.sh

**Review by phmccarty — COMMENTED** [review]
And also in swupdlib.bash, so that functional tests will pass.

**Comment by tmarcu** [comment]
Updated remaining scripts.

**Pull request merged**
