### PR TITLE
type_change: allow type change from directory to symlink

### PR DESCRIPTION
**Pull request by andred**
At least bsdtar (on the client side) seems to handle
this perfectly fine.

Signed-off-by: André Draszik <git@andred.net>

### CODE REVIEW

**Comment by andred** [comment]
I hope I didn't miss anything, but this in combination with https://github.com/clearlinux/swupd-client/pull/168 seems to work perfectly fine for me.

**Comment by andred** [comment]
I didn't actually notice https://github.com/clearlinux/swupd-server/issues/50 before, does that issue imply there is more to do?

**Comment by phmccarty** [comment]
@andred Yes, more work is needed to support a non-empty directory type change. The empty directory case is the trivial one.

I just wrote a summary of the current state at https://github.com/clearlinux/swupd-server/wiki/Type-changes.

**Comment by phmccarty** [comment]
Hmm, I see that `swupd_rm()` is called in swupd-client for this case already, so it may work okay after all. I'll revisit the client staging code.

**Comment by tmarcu** [comment]
Refer to https://github.com/clearlinux/swupd-client/issues/209 for further work on this.

**Pull request closed without merging**
